### ISSUE TITLE
Root package 'maximerenou/pi-chat' cannot require itself in its composer.json

### ISSUE THREAD

**Issue by fabthecop** [maximerenou/php-pi-chat#1]
**I get, upon installation via XAMPP on OS X Ventura:**
`Root package 'maximerenou/pi-chat' cannot require itself in its composer.json
`

**Actions:**
`
cd /Applications/XAMPP/xamppfiles/htdocs/php-pi-chat-main
`
`
composer require maximerenou/pi-chat
`

**Comment by maximerenou** [comment]
Hello,

`composer require ...` is only relevant if you want to use this package in another project. 

It looks like you cloned this repository, so you just need to run `composer install` inside it!
